<?php
/**
 * we cant get the dipendency injector from controller during the construct
 * so we have the get it in here
 */
$di = $this->_controller->getDi();

/**
 * the model was already fetched in during construct
 */
$this->collectionModel = $di->get($this->collectionModel);
$columns = $this->_dataObject->getData('columns');

$this->collectionModel->setGridData($this->_dataObject);
$this->collectionModel->initSelect();

$listData = $this->collectionModel->getList();

$data = $listData['data'];
?>
<div class="page-top-bottons d-flex justify-content-end">
	<?= $this->contentTopBottons->buttonsToHtml(); ?>
</div>

<table class="<?= $this->tableClass ?>">
	<thead>
		<tr>
			<?php 
				foreach ($columns as $key => $column) {
					$label = '';
					if(isset($column['label'])){
						$label = $column['label'];
					}
					elseif(isset($column['column_name'])){
						$label = $column['column_name'];
					}
					echo '<th scope="col">'.$label.'</th>';
				} 
			?>
		</tr>
	</thead>
	<?php if($data): ?>
		<tbody>
			<?php
				foreach ($data as $key => $value) {
					echo "<tr>";
						foreach ($columns as $_key => $_column) {
							if(isset($_column['renderer'])){
								$renderer = $di->get($_column['renderer']);
								echo "<td>".$renderer->render($value)."</td>";
							}
							else {
								echo "<td>".$value->getData($_column['column_name'])."</td>";
							}
						}
					echo "</tr>";
				}
			?>
		</tbody>
	<?php endif; ?>
</table>

<div class="pagination-container">
	<nav aria-label="Page navigation example">
		<ul class="pagination d-flex align-items-center justify-content-end">
			<li class="page-item disabled">
				<a class="page-link" href="#" tabindex="-1">Previous</a>
			</li>
			<li class="page-item ms-3 me-2">Page <input class="text-center w-50-px" type="text" value="1"></li>
			<li class="page-item me-3">of 5</li>
			<li class="page-item">
				<a class="page-link" href="#">Next</a>
			</li>
		</ul>
	</nav>
</div>

<script>
	require(['main'], function(main){
		main.pagination.init();
		console.log('main main', main);
	})
</script>