<?php
/**
 * we cant get the dipendency injector from controller during the construct
 * so we have the get it in here
 */
$di = $this->_controller->getDi();
?>
<div class="page-top-bottons d-flex justify-content-end">
	<?= $this->contentTopBottons->buttonsToHtml(); ?>
</div>

<div id="admin-grid-table" class="d-none">
	<div class="row">
		<div class="col-6">
			<?= $this->_lang->_getLang('Active Filters') ?>: 
			<div class="clearfix" v-if="filters.filters && filters.filters.search_fields.length">
				<small class="float-start mb-0 me-3" v-for="search_field of filters.filters.search_fields">
					<span v-if="search_field.type == 'text'"><span class="text-muted" >{{search_field.label}}:</span> {{search_field.search_string}}</span>
					<span v-if="search_field.type == 'range'">
						<span class="text-muted">{{search_field.label}}:</span> 
						<?= $this->_lang->_getLang('From') ?> <span v-if="search_field.from">{{search_field.from}}</span><span v-else>0</span>
						<?= $this->_lang->_getLang('To') ?> <span v-if="search_field.to">{{search_field.to}}</span><span v-else>*</span>
					</span>
					<span v-if="search_field.type == 'select'"><span class="text-muted" >{{search_field.label}}:</span> {{getOptionLabelBySearchField(search_field)}}</span>
					<a href="javascript:void(0)" v-on:click="removeFilter(search_field)"><i class="far fa-times-circle"></i></a>
				</small>
			</div>
		</div>	
		<div class="col-6">
			<v-template v-if="top_buttons">
				<div class="admin-grid-top-buttons text-end mb-3">
					<button v-if="top_buttons.filters" type="button" class="btn btn-outline-primary" v-on:click="showFiltersModal()">
						<i class="fa-solid fa-filter"></i> <?= $this->_lang->_getLang('Filters') ?>
					</button>
					<v-template v-if="top_buttons.export">
						<a href="<?= $this->getAdminUrl('grid/export/csvfile', ['listing_name' => $this->listingName]) ?>" type="button" class="btn btn-outline-secondary">
							<i class="fa-solid fa-file-export"></i> <?= $this->_lang->_getLang('Export CSV') ?>
						</a>
						<a href="javascript:void(0)" type="button" class="btn btn-outline-secondary" v-on:click="showDownloadCSVFilesModal()">
							<i class="fa-solid fa-download"></i> <?= $this->_lang->_getLang('Download CSV Files') ?>
						</a>
					</v-template>
				</div>
			</v-template>

			<div class="pagination-container d-flex align-items-center justify-content-end mb-3" v-if="filters.filters">
				<div class="d-flex align-items-center">
					<div for="pagination-limits" class="pe-0 d-block w-fit-content me-2"><?= $this->_lang->_getLang('Per Page') ?></div>
					<select class="builder-form-field form-select w-fit-content" type="select" name="status" value="" v-model="filters.filters.limit" v-on:change="changeLimitPerPage()">
						<option v-for="limit in limits" v-bind:value="limit" >{{limit}}</option>
					</select>
				</div>
				<div class="ms-2">
					<ul class="pagination d-flex align-items-center justify-content-end mb-0">
						<li class="page-item" v-if="list_data.current_page > 1">
							<a class="page-link" href="javascript:void(0)" v-on:click="goToPrevPage()">
								<i class="fa-solid fa-angles-left"></i>
							</a>
						</li>
						<li class="page-item ms-2 me-2"><?= $this->_lang->_getLang('Page') ?> <input class="text-center w-65-px" type="text" value="1" v-model="filters.filters.page" v-on:change="goToPage()"></li>
						<li class="page-item me-2"><?= $this->_lang->_getLang('of') ?> {{list_data.total_page}}</li>
						<li class="page-item" v-if="list_data.total_page > list_data.current_page">
							<a class="page-link" href="javascript:void(0)" v-on:click="goToNextPage()">
								<i class="fa-solid fa-angles-right"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>	
	</div>

	<table class="<?= $this->tableClass ?>">
		<thead class="table-dark" v-if="columns">
			<tr>
				<th scope="col" v-for="column in columns" v-on:click="setOrderBy(column)">
					{{column.label}}
					<div class="float-end" v-if="column.column_name == filters.filters.sort_order.order_by">
						<i class="fa-solid fa-arrow-down-long" v-if="filters.filters.sort_order.direction == 'asc'"></i>
						<i class="fa-solid fa-arrow-up-long" v-if="filters.filters.sort_order.direction == 'desc'"></i>
					</div>
				</th>
			</tr>
		</thead>
		<tbody v-if="list_data">
			<tr v-for="field in list_data.data">
				<td v-for="column in columns" v-html="field[column.column_name]"></td>
			</tr>
		</tbody>
	</table>

	<div class="pagination-container d-flex align-items-center justify-content-end" v-if="filters.filters">
		<div class="d-flex align-items-center">
			<div for="pagination-limits" class="pe-0 d-block w-fit-content me-2"><?= $this->_lang->_getLang('Per Page') ?></div>
			<select class="builder-form-field form-select w-fit-content" type="select" name="status" value="" v-model="filters.filters.limit" v-on:change="changeLimitPerPage()">
				<option v-for="limit in limits" v-bind:value="limit" >{{limit}}</option>
			</select>
		</div>
		<div class="ms-2">
			<ul class="pagination d-flex align-items-center justify-content-end mb-0">
				<li class="page-item" v-if="list_data.current_page > 1">
					<a class="page-link" href="javascript:void(0)" v-on:click="goToPrevPage()">
						<i class="fa-solid fa-angles-left"></i>
					</a>
				</li>
				<li class="page-item ms-2 me-2"><?= $this->_lang->_getLang('Page') ?> <input class="text-center w-65-px" type="text" value="1" v-model="filters.filters.page" v-on:change="goToPage()"></li>
				<li class="page-item me-2"><?= $this->_lang->_getLang('of') ?> {{list_data.total_page}}</li>
				<li class="page-item" v-if="list_data.total_page > list_data.current_page">
					<a class="page-link" href="javascript:void(0)" v-on:click="goToNextPage()">
						<i class="fa-solid fa-angles-right"></i>
					</a>
				</li>
			</ul>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="admin-grid-filters-modal" tabindex="-1" role="dialog" aria-labelledby="adminGridFiltersModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="adminGridFiltersModalLabel"><?= $this->_lang->_getLang('Filters') ?></h5>
					<button type="button" class="close btn" data-bs-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<v-template v-if="columns">
						<v-template v-for="column in columns">
							<v-template v-if="column.filter">
								<div class="form-group mb-3" v-if="column.filter.type == 'text'">
									<label v-bind:for="'admin-grid-filter-'+column.column_name">{{column.label}}</label>
									<input type="text" class="form-control" v-bind:id="'admin-grid-filter-'+column.column_name" v-on:keyup="updateFilter(column.filter.type, column, $event, '')" />
								</div>
								<div class="form-group mb-3 row" v-if="column.filter.type == 'range'">
									<div class="col-6">
										<label v-bind:for="'admin-grid-filter-'+column.column_name+'-from'">{{column.label}} From</label>
										<input type="text" class="form-control" v-bind:id="'admin-grid-filter-'+column.column_name+'-from'" v-on:keyup="updateFilter(column.filter.type, column, $event, 'from')" />
									</div>
									<div class="col-6">
										<label v-bind:for="'admin-grid-filter-'+column.column_name+'-to'">{{column.label}} To</label>
										<input type="text" class="form-control" v-bind:id="'admin-grid-filter-'+column.column_name+'-to'" v-on:keyup="updateFilter(column.filter.type, column, $event, 'to')" />
									</div>
								</div>
								<div class="form-group mb-3" v-if="column.filter.type == 'select'">
									<label v-bind:for="'admin-grid-filter-'+column.column_name">{{column.label}}</label>
									<select class="form-select" v-bind:id="'admin-grid-filter-'+column.column_name" v-on:change="updateFilter(column.filter.type, column, $event, '')">
										<option value="">Select {{column.label}}</option>
										<option v-for="option in column.filter.option" v-bind:value="option.key">{{option.value}}</option>
									</select>
								</div>
							</v-template>
						</v-template>
					</v-template>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><?= $this->_lang->_getLang('Close') ?></button>
					<button type="button" class="btn btn-primary" v-on:click="applyFilter()"><?= $this->_lang->_getLang('Apply Filters') ?></button>
				</div>
			</div>
		</div>
	</div>

	
	<div class="modal fade" id="admin-grid-exported-csv-files-modal" tabindex="-1" role="dialog" aria-labelledby="adminGridExportedCsvFilesModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="adminGridExportedCsvFilesModalLabel"><?= $this->_lang->_getLang('Exported CSV Files') ?></h5>
					<button type="button" class="close btn" data-bs-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<v-template v-if="!exportedCsvFiles">
						<div class="row">
							<div class="col-12">
								<p class="skeleton-box" style="width: 70%; height: 16px;"></p>
								<p class="skeleton-box" style="width: 65%; height: 14px;"></p>
								<p class="skeleton-box" style="width: 87%; height: 14px;"></p>
							</div>
						</div>
					</v-template>
					<v-template v-if="exportedCsvFiles && exportedCsvFiles['data']">
						<div class="row" v-if="exportedCsvFiles['data'].length">
							<div class="col-12">
								<table class="table table-striped table-hover"> 
									<tbody>
										<tr v-for="exportedFile in exportedCsvFiles['data']">
											<td>
												<small class="m-0 d-block" >{{exportedFile.generated_file}}</small>
												<small class="m-0 d-block">
													<span class="badge bg-secondary" v-if="exportedFile.status == 'pending'">{{exportedFile.status}}</span>
													<span class="badge bg-success" v-if="exportedFile.status == 'done'">{{exportedFile.status}}</span>
													<span class="badge bg-warning" v-if="exportedFile.status == 'active'">{{exportedFile.status}}</span>
												</small>
												<small class="m-0 d-block" >{{exportedFile.current_count}} <?= $this->_lang->_getLang('of') ?> {{exportedFile.total_count}}</small>
											</td>
											<td>
												<a class="me-2" v-if="exportedFile.status == 'done'" v-bind:href="getExportedFileDownloadLink(exportedFile)" title="Download">
													<i class="fa-solid fa-download"></i>
												</a>
												<a href="javascript:void(0)" title="Delete" v-on:click="deleteExportedFileConfirm(exportedFile)">
													<i class="fa-solid fa-trash-can"></i>
												</a>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="row" v-if="!exportedCsvFiles['data'].length">
							<p class="text-center">
								<?= $this->_lang->_getLang('No exported data found') ?>
							</p>
						</div>
					</v-template>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	require([
		'opoink/bmodule/js/admin/ui.components.grid.min'
	], function(grid){
		grid._data.setListingName('<?= $this->listingName ?>').getListing();
	});
</script>