<script src="<?= $this->getPublicUrl('/opoink/bmodule/js/require.js') ?>"></script>

<script>
	const adminUrl = '<?= $this->getAdminUrl() ?>';
	requirejs.config({
		baseUrl: '<?= $this->getPublicUrl() ?>',
		paths: {
			"jquery":  "<?= $this->getPublicUrl('/opoink/bmodule/js/jquery') ?>",
			"bootstrap": 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min',
			"main": "<?= $this->getPublicUrl('/opoink/bmodule/js/admin/main.min') ?>",
			"vue": "<?= $this->getPublicUrl('/opoink/bmodule/js/admin/vue') ?>",
			"request": "<?= $this->getPublicUrl('/opoink/bmodule/js/admin/request.min') ?>",
			"validatorjs": "<?= $this->getPublicUrl('/opoink/bmodule/js/validatorjs.3.22.0.min') ?>", <?php /** https://www.npmjs.com/package/validatorjs */ ?>
			"storage": "<?= $this->getPublicUrl('/opoink/bmodule/js/admin/services/storage.min') ?>"
		},
		shim: {
			"bootstrap": {
				deps: ["jquery"],
				exports: '$'
			}
		},
		attributes: {
			"bootstrap": {
				integrity: "sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p",
				crossorigin: "anonymous"
			},
			"main": {
				type: "module"
			}
		},
		onNodeCreated: function(node, config, name, url){
			if(config.attributes && config.attributes[name]){
				Object.keys(config.attributes[name]).forEach(attribute => {
					node.setAttribute(attribute, config.attributes[name][attribute]);
				});
			}
		}
	});

	require([
		'bootstrap',
		'main' 
	], (main) => {});
</script>

<?php
/*
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script src="<?= $this->getPublicUrl("/opoink/bmodule/js/jquery.js") ?>"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
*/
?>