<?php
	$adminUser = $this->getAdminUser();
?>

<div class="main-header">
	<div class="float-start h-100 d-flex align-items-center">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="toggle-side-nav navbar-brand ms-3 me-3" href="javascript:void(0)">
				<i class="fa-solid fa-bars"></i>
			</a>
		</nav>
	</div>
	<div class="float-end h-100 d-flex align-items-center">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="collapse navbar-collapse">
				<ul class="navbar-nav mr-auto">
					<?php
					// <li class="nav-item active">
					// 	<a class="nav-link" href="#">Home</a>
					// </li>
					// <li class="nav-item">
					// 	<a class="nav-link" href="#">Link</a>
					// </li>
					// <li class="nav-item">
					// 	<a class="nav-link" href="#">Disabled</a>
					// </li>
					?>
					<li class="nav-item dropdown me-2">
						<a class="nav-link dropdown-toggle" href="javascript:void(0)" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Language
						</a>
						<div class="dropdown-menu dropdown-menu-end me-2" aria-labelledby="header-admin-user-dropdown">
							<a class="dropdown-item" href="<?= $this->getAdminUrl('language') ?>">
								en
							</a>
							<a class="dropdown-item" href="<?= $this->getAdminUrl('language') ?>">
								tgl
							</a>
						</div>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="javascript:void(0)" id="header-admin-user-dropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-user me-2"></i> <?= $adminUser->getData('firstname'); ?> <?= $adminUser->getData('lastname') ?>
						</a>
						<div class="dropdown-menu dropdown-menu-end me-2" aria-labelledby="header-admin-user-dropdown">
							<a class="dropdown-item" href="<?= $this->getAdminUrl('adminuser/profile') ?>">
								Profile Settings
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="<?= $this->getAdminUrl('logout') ?>">
								Logout
							</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>
	</div>
</div>