<div class="menu-header">
	
	<div class="side-menu-icon menu-header-logo">
		<img src="<?= $this->getImageUrl([
			'vendor'=>'Opoink',
			'module'=>'Bmodule',
			'path' => '/images',
			'filename' => 'default-logo.png'
		]) ?>">
	</div>

	<div class="side-menu-label menu-header-label">
		<span class="fw-800">Opoink</span> Admin
		
		<button type="button" class="close toggle-side-nav" v-on:click="toggleSideNav()">
			<span><i class="fa-solid fa-arrow-left"></i></span>
		</button>
	</div>
</div>
<div class="menu-body-container">
	<div class="menu-body">
		<?php echo $this->getChildHtml(); ?>
	</div>
</div>