<div id="general-notification-container" class="general_notification_container">
	<ul class="general_notification">
		<?php
			$messages = $this->_message->getMessage();
			if($messages){
				foreach($messages as $mesKey => $mesVal){
					$type = $mesVal['type'];
					echo "
					<li class='general_notification_message alert alert-".$type." toast-msg-".$mesKey."'>
						<div class='m-0'>{$mesVal['message']}</div>
						<button class='notificationMessageClose' v-on:click=\"removeMesg('".$mesKey."', true)\">
							<i class='far fa-times-circle'></i>
						</button>
					</li>";
				}
				$this->_message->unsetData('__message');
			}
		?>

		<li v-for="(msg, key) in messages" v-bind:class="'general_notification_message alert alert-'+msg.type+' toast-msg-0'">
			<div class="m-0"v-html="msg.message"></div>
			<button class="notificationMessageClose" v-on:click="removeMesg(key)">
				<i class="far fa-times-circle"></i>
			</button>
		</li>
	</ul>
</div>
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="confirmationModalLabel">Title</h5>
				<button type="button" class="btn close" data-bs-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
				<button type="button" class="btn btn-primary">Yes</button>
			</div>
		</div>
	</div>
</div>