<?php
	echo $this->_message->toHtml();
?>
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="confirmationModalLabel">Title</h5>
				<button type="button" class="btn close" data-bs-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
				<button type="button" class="btn btn-primary">Yes</button>
			</div>
		</div>
	</div>
</div>
<script>
	require([
		'jquery'
	], function($){
		$('.general_notification_container .notificationMessageClose').on('click', (e) => {
			$('.general_notification_container .toast-msg-'+e.delegateTarget.dataset.index).remove();
			console.log('notificationMessageClose', e.delegateTarget.dataset.index);
		});
	});
</script>