<?php
	$tab = $this->_controller->getParam('tab');
	if($tab) {
		$tab = strtolower($tab);
	}

	$collapsed = 'collapsed';
	$ariaExpanded = 'false';
	$sub = '';
	if($tab == 'general'){
		$collapsed = 'collapsed';
		$ariaExpanded = 'true';
		$sub = 'show';
	}
?>

<div class="settings-left-tab">
	<div class="settings-tab-control <?= $collapsed ?>" data-bs-toggle="collapse" data-bs-target="#settings-left-tab-general-sub" aria-expanded="<?= $ariaExpanded ?>" aria-controls="settings-left-tab-general-sub">
		<?= $this->_lang->_getLang('General') ?>
	</div>
	<ul id="settings-left-tab-general-sub" class="settings-left-tab-sub collapse <?= $sub ?>">
		<?= $this->getChildHtml() ?>
	</ul>
</div>