<?php
	$groups = $this->getFields();
?>
<?php if($this->currentTab && $this->currentSubTab): ?>
	<div class="settings-form-fields">
		<?php foreach ($groups as $group => $fields): ?>
			<div class="group">
				<div class="group-name collapsed" data-bs-toggle="collapse" data-bs-target=".form-group-<?= $group ?>-container" aria-expanded="false">
					<?= $this->_lang->_getLang(ucfirst(str_replace('_', ' ', $group))) ?>
				</div>
				<div class="collapse form-group-<?= $group ?>-container p-4">
					<?php $form = $this->_formBuilder->form([
						'action' => $this->getAdminUrl('/settings/savesettings', $this->_request->getParam()),
						'method' => 'POST',
						'class' => 'form-group-' . $group
					]); ?>
					<?php foreach ($fields as $fieldKey => $field): ?>
						<?php
							if(isset($field['label'])){
								$field['label'] = $this->_lang->_getLang($field['label']);
							}

							$settingPath = $this->currentTab.'/'.$this->currentSubTab.'/'.$group.'/'.$fieldKey.'/value';

							$field['attributes']['name'] = $fieldKey;
							$field['attributes']['value'] = $this->_settings->getSettings($settingPath);

							// if(!isset($field['comment'])){
							// 	$field['comment'] = [];
							// }
							// $field['comment'][] = [
							// 	"text" => 'Leave empty, to use the system default value',
							// 	"class" => 'text-muted d-block m-0',
							// ];
							// $field['comment'][] = [
							// 	"text" => 'To get value: $this->_settings->getSettings('.$settingPath.')',
							// 	"class" => 'text-muted d-block m-0',
							// ];
							$this->_formBuilder->add($form, $field, true);
						?>
					<?php endforeach ?>

					<?php 
						$this->_formBuilder->add($form, [ 
							'label' => "settings_key",
							"attributes" => [
								"type" => "hidden",
								"name" => "settings_key",
								"value" => $this->currentTab.'/'.$this->currentSubTab.'/'.$group.'/',
								"class" => ""
							]
						]); 

						$this->_formBuilder->add($form, [ 
							'label' => "Save",
							"attributes" => [
								"type" => "button",
								"name" => "save_settings",
								"value" => "1",
								"class" => "btn-primary mt-3"
							],
							"position" => "end"
						], true); 
					?>
					<?= $this->_formBuilder->toHtml($form); ?>
				</div>
			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>