<?php
	$groups = $this->getFields();
?>
<?php if($this->currentTab && $this->currentSubTab): ?>
	<div class="settings-form-fields">
		<?php foreach ($groups as $group => $fields): ?>
			<div class="group">
				<div class="group-name collapsed" data-bs-toggle="collapse" data-bs-target=".form-group-<?= $group ?>-container" aria-expanded="false">
					<?= $group ?>
				</div>
				<div class="collapse form-group-<?= $group ?>-container p-4">
					<?php $form = $this->_formBuilder->form([
						'action' => $this->getAdminUrl('/settings/savesettings'),
						'method' => 'POST',
						'class' => 'form-group-' . $group
					]); ?>
					<?php foreach ($fields as $fieldKey => $field): ?>
						<?php
							$field['attributes']['value'] = $this->_settings->getSettings($this->currentTab.'/'.$this->currentSubTab.'/'.$group.'/'.$fieldKey.'/value');
							$this->_formBuilder->add($form, $field, true);
						?>
					<?php endforeach ?>

					<?php 
						$this->_formBuilder->add($form, [ 
							'label' => "Save",
							"attributes" => [
								"type" => "button",
								"name" => "save_settings",
								"value" => "1",
								"class" => "btn-primary mt-3"
							],
							"position" => "end"
						], true); 
					?>
					<?= $this->_formBuilder->toHtml($form); ?>
				</div>
			</div>
		<?php endforeach ?>
	</div>
<?php endif ?>